name: 'Doxygenize'
description: 'Generate Doxygen code documentation and publish it to GitHub Pages'
branding:
  icon: 'book'
  color: 'orange'
inputs:
  doxygenconf:
    description: 'Doxygen configuration file path'
    required: true
    default: './Doxyfile'
  htmloutput:
    description: 'Generated HTML documents output folder'
    required: true
    default: './docs/'
  ghpagesbranch:
    description: 'GitHub Pages branch name'
    required: true
    default: 'gh-pages'
  ghpagesdir:
    description: 'GitHub Pages directory path'
    required: true
    default: './'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.doxygenconf }}
  - ${{ inputs.htmloutput }}
  - ${{ inputs.ghpagesbranch }}
  - ${{ inputs.ghpagesdir }}